name: Build and deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir build
      
      - name: Build html
        uses: docker://pandoc/core:3-ubuntu
        with:
          args: >-
            --from org --to html
            --standalone
            --toc --toc-depth 2
            -o build/index.html
            README.org
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
